FORMAT: 1A
HOST: http://pools.apiblueprint.org/

# niuhome 

牛家帮APP  API

###### 
## 首页接口 [/index]

### app 首页[POST]
###### 有时间可优化此列表 将过去的2个banner和建议接口合并为一个接口，较少请求数
+ Response 200 (application/json)

        [
            {
                "question": "listtutoral1212",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift1",
                        "votes": 2048
                    },
                    {
                        "choice": "Swift2",
                        "votes": 204323
                    },
                    {
                        "choice": "Python1",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C1",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]


## 收纳 [/shouna/toolList]
### 收纳工具列表 [POST]

单行显示 图片，收纳工具名称（价格），收纳工具描述做什么的，
收纳工具列表，根据上传时间降序排序 索性服务器端排个时间倒序吧

#### 返回 code 108是成功的接口
#### id   收纳工具id 1
#### image 暂时app内置图片 以后有机会改成网络获取

+ Response 201 (application/json)

    + Body

            {
                "code": "108",
                "list": [
                    {
                        "id": "1",
                        "image": "",
                        "price": "5",
                        "desc": "收纳200个袜神器只要5元"
                    },  
                    {
                        "id": "2",
                        "image": "",
                        "price": "10",
                        "desc": "西装收纳套"
                    }, 
                ]
            }


## 收纳订单提交 [/shouna/payCommit]
### 收纳订单提交 [POST]

单行显示 图片，收纳工具名称（价格），收纳工具描述做什么的，
收纳工具列表，根据上传时间降序排序 索性服务器端排个时间倒序吧

#### 返回 code 108是成功的接口
#### id   收纳工具id 1
#### image 暂时app内置图片 以后有机会改成网络获取

+ Response 201 (application/json)
    
    + Body

            {
                "code": "108",
                "list": [
                    {
                        "id": "1",
                        "image": "",
                        "price": "5",
                        "desc": "收纳200个袜神器只要5元"
                    },  
                    {
                        "id": "2",
                        "image": "",
                        "price": "10",
                        "desc": "西装收纳套"
                    }, 
                ]
            }



