FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# niuhome 

牛家帮APP  API

###### 
## 首页接口 [/index]

### app 首页[POST]
###### 有时间可优化此列表 将过去的2个banner和建议接口合并为一个接口，较少请求数
+ Response 200 (application/json)

        [
            {
                "question": "listtutoral1212",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift1",
                        "votes": 2048
                    },
                    {
                        "choice": "Swift2",
                        "votes": 204323
                    },
                    {
                        "choice": "Python1",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C1",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]


## 收纳相关 [/shouna]
### 列表 [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
